### ISSUE TITLE
Add hide scrollbars tool

### ISSUE THREAD

**Issue by hatzipanis** [batchnz/bcss#4]
```css
overflow-x: hidden;
overflow-y: auto;
-ms-overflow-style: -ms-autohiding-scrollbar;
overflow: -moz-scrollbars-none;
&::-moz-scrollbar, 
&::-webkit-scrollbar {
    display: none;
}
```
